language: node_js
node_js:
  - "10.7.0"

script:
  - npm install
  - npm run build
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build -t cjblink1/mergeaftertoll-web-app:$TRAVIS_BRANCH-$TRAVIS_COMMIT .
  - docker push cjblink1/mergeaftertoll-web-app:$TRAVIS_BRANCH-$TRAVIS_COMMIT
  # - curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.11.0/bin/linux/amd64/kubectl
  # - chmod +x kubectl
  # - mv kubectl ~/bin/kubectl
  # - kubectl config set-cluster kubernetes --server=${CLUSTER_ADDRESS}
  # - kubectl config set clusters.kubernetes.certificate-authority-data ${CA_DATA}
  # - kubectl config set-context kubernetes --cluster=kubernetes
  # - kubectl config use-context kubernetes
  # - kubectl config view
  # - kubectl version