apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: mergeaftertoll-certificate
  namespace: default
spec:
  secretName: mergeaftertoll-certs
  issuerRef:
    name: letsencrypt-prod-cluster-issuer
    kind: ClusterIssuer
  commonName: 294.cjblink1.pro
  dnsNames:
  - 294.cjblink1.pro
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - 294.cjblink1.pro